// <auto-generated />
using System;
using ADPasswordRotator.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADPasswordRotator.Backend.Migrations
{
    [DbContext(typeof(ADContext))]
    [Migration("20240526042523_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.CheckinEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DomainControllerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceAccountId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DomainControllerId");

                    b.HasIndex("ServiceAccountId");

                    b.ToTable("CheckinEntry");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.DomainController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckinIntervalType")
                        .HasColumnType("int");

                    b.Property<int>("CheckinIntervalValue")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastCheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("DomainControllers");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.ServiceAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckinIntervalType")
                        .HasColumnType("int");

                    b.Property<int>("CheckinIntervalValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPasswordReset")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId1")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasswordResetIntervalType")
                        .HasColumnType("int");

                    b.Property<int>("PasswordResetIntervalValue")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("LocationId1");

                    b.ToTable("ServiceAccounts");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.SettingsOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Internal")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SettingsOptions");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.CheckinEntry", b =>
                {
                    b.HasOne("ADPasswordRotator.Shared.Model.DomainController", null)
                        .WithMany("CheckinEntries")
                        .HasForeignKey("DomainControllerId");

                    b.HasOne("ADPasswordRotator.Shared.Model.ServiceAccount", null)
                        .WithMany("CheckinEntries")
                        .HasForeignKey("ServiceAccountId");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.DomainController", b =>
                {
                    b.HasOne("ADPasswordRotator.Shared.Model.Location", "Location")
                        .WithMany("Controllers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.ServiceAccount", b =>
                {
                    b.HasOne("ADPasswordRotator.Shared.Model.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ADPasswordRotator.Shared.Model.Location", null)
                        .WithMany("Accounts")
                        .HasForeignKey("LocationId1");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.DomainController", b =>
                {
                    b.Navigation("CheckinEntries");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.Location", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Controllers");
                });

            modelBuilder.Entity("ADPasswordRotator.Shared.Model.ServiceAccount", b =>
                {
                    b.Navigation("CheckinEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
